### PR TITLE
make lib functional

### PR DESCRIPTION
**Pull request by Dragonizedpizza**
adds many updates, and actually makes the lib functional.

### CODE REVIEW

**Comment by somerandomcloud** [comment]
Can you elaborate on "add many update"? I dont see much that changed except formatting

**Comment by Dragonizedpizza** [comment]
> Can you elaborate on "add many update"? I dont see much that changed except formatting

not formatting, reworking
formatting is making it look different, reworking is actually updating the lib

**Comment by Dragonizedpizza** [comment]
before you were updating the options object prototype, constantly updating the url
using one function:
```js
options.url = `${options.url}/api/some/endpoint/`; // https://some-site-host.com/api/users/id
```
you've changed the options object's url property value entirely.
now, using another function would make it `https://some-site-host.com/api/users/id/servers/id`

**Comment by somerandomcloud** [comment]
Yeah I must have forgotten did a mistake... Will pull rn as its a really needed fix

**Pull request merged**
